///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RegressionTest_Project
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RegressionTest_ProjectRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("709341ba-1eb8-4b33-993b-95ac57749535")]
    public partial class RegressionTest_ProjectRepository : RepoGenBaseFolder
    {
        static RegressionTest_ProjectRepository instance = new RegressionTest_ProjectRepository();
        RegressionTest_ProjectRepositoryFolders.ExplorerAppFolder _explorer;

        /// <summary>
        /// Gets the singleton class instance representing the RegressionTest_ProjectRepository element repository.
        /// </summary>
        [RepositoryFolder("709341ba-1eb8-4b33-993b-95ac57749535")]
        public static RegressionTest_ProjectRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RegressionTest_ProjectRepository() 
            : base("RegressionTest_ProjectRepository", "/", null, 0, false, "709341ba-1eb8-4b33-993b-95ac57749535", ".\\RepositoryImages\\RegressionTest_ProjectRepository709341ba.rximgres")
        {
            _explorer = new RegressionTest_ProjectRepositoryFolders.ExplorerAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("709341ba-1eb8-4b33-993b-95ac57749535")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("a78050dd-77b7-4c4a-907f-b77f5501fa70")]
        public virtual RegressionTest_ProjectRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class RegressionTest_ProjectRepositoryFolders
    {
        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("a78050dd-77b7-4c4a-907f-b77f5501fa70")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _list1Info;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/desktop[@processname='explorer']", parentFolder, 30000, null, true, "a78050dd-77b7-4c4a-907f-b77f5501fa70", "")
            {
                _list1Info = new RepoItemInfo(this, "List1", "?/?/list[@controlid='1']", 30000, null, "8117742b-a5cc-490c-9810-8056dfd82b29");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a78050dd-77b7-4c4a-907f-b77f5501fa70")]
            public virtual Ranorex.Desktop Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Desktop>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a78050dd-77b7-4c4a-907f-b77f5501fa70")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The List1 item.
            /// </summary>
            [RepositoryItem("8117742b-a5cc-490c-9810-8056dfd82b29")]
            public virtual Ranorex.List List1
            {
                get
                {
                    return _list1Info.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The List1 item info.
            /// </summary>
            [RepositoryItemInfo("8117742b-a5cc-490c-9810-8056dfd82b29")]
            public virtual RepoItemInfo List1Info
            {
                get
                {
                    return _list1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}